NAME = "Dra. Monyque Cunha Trindade"
ESPECIALIDADE = "CIRURGIA BUCOMAXILOFACIAL"
FOOTER = "Clínica Bioethos: Rua Padre Montoya, 300 - Centro - CEP 85851-080, Foz do Iguaçu - PR\nTel: (45) 3028-1282 - Whats: (45) 98805-0334 - www.dramonyquebucomaxilo.com.br"
TERMO_NAME = "Dra. Monyque Cunha Trindade - Cirurgia Bucomaxilofacial"
TERMO_TXT = "TERMO DE CONSENTIMENTO LIVRE E ESCLARECIDO"
